
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-7pm-3
owner: ucsb-cs156-w24
repo_name: team02-w24-7pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjIzNDM4MzQ2","is_bot":false,"login":"calee14","name":"Cappillen Lee"},"headRefName":"cl-UCSBDiningCommonsMenuItem-get","number":50,"title":"Add GET (show) endpoint for a single record in UCSBDiningCommonsMenuItem table","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-3/pull/50"},{"author":{"id":"MDQ6VXNlcjIzNDM4MzQ2","is_bot":false,"login":"calee14","name":"Cappillen Lee"},"headRefName":"cl-UCSBDiningCommonsMenuItem-controller","number":49,"title":"Create UCSBDiningCommonsMenuItemController, add GET (index) and POST (create)","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-3/pull/49"},{"author":{"id":"MDQ6VXNlcjIzNDM4MzQ2","is_bot":false,"login":"calee14","name":"Cappillen Lee"},"headRefName":"cl-UCSBDiningCommonsMenuItem-create-db","number":48,"title":"Create database table for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-3/pull/48"},{"author":{"id":"MDQ6VXNlcjY0MzI4MjM0","is_bot":false,"login":"Rytuose","name":""},"headRefName":"Ryan-MenuReviewTable-putendpoint","number":47,"title":"Implement put option for menu item review","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-3/pull/47"},{"author":{"id":"MDQ6VXNlcjY0MzI4MjM0","is_bot":false,"login":"Rytuose","name":""},"headRefName":"Ryan-MenuReviewTable-deleteendpoint","number":46,"title":"Ryan menu review table deleteendpoint","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-3/pull/46"},{"author":{"id":"MDQ6VXNlcjY0MzI4MjM0","is_bot":false,"login":"Rytuose","name":""},"headRefName":"Ryan-MenuReviewTable-getendpoint","number":45,"title":"Added get endpoint for Menu Item Review","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-3/pull/45"},{"author":{"id":"MDQ6VXNlcjY0MzI4MjM0","is_bot":false,"login":"Rytuose","name":""},"headRefName":"Ryan-MenuReviewTable-reviewcontroller","number":44,"title":"Added MenuItemReview Controller and the get and post commands","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-3/pull/44"},{"author":{"id":"MDQ6VXNlcjY0MzI4MjM0","is_bot":false,"login":"Rytuose","name":""},"headRefName":"Ryan-MenuReviewTable-create-db","number":43,"title":"DB Table for Menu Item Review","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-3/pull/43"}]
