
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-7pm-3
owner: ucsb-cs156-w24
repo_name: team02-w24-7pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjY4MTY0Njk0","is_bot":false,"login":"cydthe","name":""},"headRefName":"cg-UCSBOrganizationsControllerTests","number":60,"title":"Adding UCSBOrganizations Controller Tests","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-3/pull/60"},{"author":{"id":"MDQ6VXNlcjY4MTY0Njk0","is_bot":false,"login":"cydthe","name":""},"headRefName":"cg-UCSBOrgsControllers","number":59,"title":"Creating UCSBOrganizations controller  ","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-3/pull/59"},{"author":{"id":"MDQ6VXNlcjY4MTY0Njk0","is_bot":false,"login":"cydthe","name":""},"headRefName":"cg-UCSBOrganization-create-db","number":58,"title":"creating UCSBOrganizations Database","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-3/pull/58"}]
